server:
  port: 8080
spring:
    freemarker:
      request-context-attribute: request
      allow-request-override: false
      charset: utf-8
      check-template-location: true
      template-loader-path: classpath:/WEB-INF/views/
      suffix: .ftl

ibk:
  order:
    regist:
      url: http://www.inbko.co.kr/api/order_regist_e.asp
    delete:
      url: http://www.inbko.co.kr/api/order_delete.asp
  userid: test55
  authkey: 9EE98412A7BCC9B6FD48EDF6CB06DE91
